// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB1LUEeje1U2FVHsUGe7pAp7bj6AnmNJg',
    appId: '1:973709397226:web:f25ad13eea8bc527ae1b93',
    messagingSenderId: '973709397226',
    projectId: 'bodyweight-workout',
    authDomain: 'bodyweight-workout.firebaseapp.com',
    databaseURL: 'https://bodyweight-workout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyweight-workout.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJeWq4RgRXJxXEvEZh-8pVvYxzUZSrB4',
    appId: '1:973709397226:android:886e8e555495db8bae1b93',
    messagingSenderId: '973709397226',
    projectId: 'bodyweight-workout',
    databaseURL: 'https://bodyweight-workout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyweight-workout.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB1LUEeje1U2FVHsUGe7pAp7bj6AnmNJg',
    appId: '1:973709397226:web:07f2ae6f0ebdff43ae1b93',
    messagingSenderId: '973709397226',
    projectId: 'bodyweight-workout',
    authDomain: 'bodyweight-workout.firebaseapp.com',
    databaseURL: 'https://bodyweight-workout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyweight-workout.firebasestorage.app',
  );
}